### ISSUE TITLE
docker-compose scale server has port issues

### ISSUE THREAD

**Issue by nitin-amp** [markito/geode-docker#2]
Tried starting containers using docker-compose. Initial startup of locator and server works well, however, scaling of the cluster fails - error message below:

```
$ docker-compose scale server=3
WARNING: The "server" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting 2 ... error
Creating and starting 3 ... error

ERROR: for 2  failed to create endpoint composer_server_2 on network bridge: Bind for 0.0.0.0:40404 failed: port is already allocated
ERROR: for 3  failed to create endpoint composer_server_3 on network bridge: Bind for 0.0.0.0:40404 failed: port is already allocated

```

Does this script require an update?

**Comment by viacheslavtar** [comment]
@nitin-amp I've faced this issue, and replacing `"40404:40404"` with `"40404"` in the `docker-compose.yml` file helped. I see that this value was changed back and forth earlier (504e6f8, eeabba7). I'm wrapping my head around Geode and this container, it would be great if @markito could provide more details about scaling and this port value.

**Comment by nitin-amp** [comment]
Yes, this may appear to be confusing. I've gone back and forth in my compose files as well.

- If you want to run multiple servers, then port-forwarding to the host for the same port (40404) will not work due to conflicts, hence the error. Your fix takes care of it

- However, if you want to run a single server and try to connect a client directly to the server, then you may use "40404:40404"

If I may ask, what is your use-case?

**Comment by markito** [comment]
I've just replied on the geode@dev list but please let me know if you have more questions.  Long story short, that port mapping on the docker just matter if your client is running outside of the container and if that's the case I don't know another way to scale with Compose and avoid the port conflict as well.

**Comment by viacheslavtar** [comment]
@nitin-amp thanks for the details! Sorry, use cases and evaluation scenarios are somewhat off topic.

@markito thank you, it definitely makes sense. With the latest commit scaling works, so this issue might be closed.
