### ISSUE TITLE
Multiple Docker hosts

### ISSUE THREAD

**Issue by SergiuCip** [markito/geode-docker#6]
Hi,

Thanks for this, it is really useful.

Could you also provide an example of running this as a cluster on 2 Docker hosts please?

**Comment by markito** [comment]
There are a couple of ways to deal with that... One example is using docker-compose and is available here - https://github.com/markito/geode-docker/blob/master/composer/docker-compose.yml

Alternatively you can check the Kubernetes example which provides a better approach than compose IMO.  https://github.com/markito/geode-kubernetes  

Hope that helps.
